imports:
  - { resource: core_application_services.yml }
  - { resource: core_domain_services.yml }
  - { resource: core_infrastructure_services.yml }
  - { resource: core_repositories_implementation.yml }
  - { resource: core_domain_event_handlers.yml }